;;; lang/web/+html.el -*- lexical-binding: t; -*-

(package! web-mode
              :mode "\\.[px]?html?\\'"
              :mode "\\.\\(?:tpl\\|blade\\)\\(?:\\.php\\)?\\'"
              :mode "\\.erb\\'"
              :mode "\\.[lh]?eex\\'"
              :mode "\\.jsp\\'"
              :mode "\\.as[cp]x\\'"
              :mode "\\.ejs\\'"
              :mode "\\.hbs\\'"
              :mode "\\.mustache\\'"
              :mode "\\.svelte\\'"
              :mode "\\.twig\\'"
              :mode "\\.jinja2?\\'"
              :mode "\\.eco\\'"
              :mode "wp-content/themes/.+/.+\\.php\\'"
              :mode "templates/.+\\.php\\'"
              :init
              ;; If the user has installed `vue-mode' then, by appending this to
              ;; `auto-mode-alist' rather than prepending it, its autoload will have
              ;; priority over this one.
              (add-to-list 'auto-mode-alist '("\\.vue\\'" . web-mode) 'append)
              :mode "\\.vue\\'"
              :config

              ;; tidy is already defined by the format-all package. We redefine it to add
              ;; more sensible arguments to the tidy command.
              ;; (set-formatter! 'html-tidy
              ;;   '("tidy" "-q" "-indent"
              ;;     "--tidy-mark" "no"
              ;;     "--drop-empty-elements" "no"
              ;;     ("--show-body-only" "%s" (if +format-region-p "true" "auto"))
              ;;     ("--indent-spaces" "%d" tab-width)
              ;;     ("--indent-with-tabs" "%s" (if indent-tabs-mode "yes" "no"))
              ;;     ("-xml" (memq major-mode '(nxml-mode xml-mode))))
              ;;   :ok-statuses '(0 1))

              (setq web-mode-enable-html-entities-fontification t
                    web-mode-auto-close-style 1)

              (after! smartparens
                      (defun +web-is-auto-close-style-3 (_id action _context)
                        (and (eq action 'insert)
                             (eq web-mode-auto-close-style 3)))
                      (sp-local-pair 'web-mode "<" ">" :unless '(:add +web-is-auto-close-style-3))

                      ;; let smartparens handle these
                      (setq web-mode-enable-auto-quoting nil
                            web-mode-enable-auto-pairing t)

                      ;; 1. Remove web-mode auto pairs whose end pair starts with a latter
                      ;;    (truncated autopairs like <?p and hp ?>). Smartparens handles these
                      ;;    better.
                      ;; 2. Strips out extra closing pairs to prevent redundant characters
                      ;;    inserted by smartparens.
                      (dolist (alist web-mode-engines-auto-pairs)
                        (setcdr alist
                                (cl-loop for pair in (cdr alist)
                                         unless (string-match-p "^[a-z-]" (cdr pair))
                                         collect (cons (car pair)
                                                       (string-trim-right (cdr pair)
                                                                          "\\(?:>\\|]\\|}\\)+\\'")))))
                      (cl-callf2 delq nil web-mode-engines-auto-pairs))

              (add-to-list 'web-mode-engines-alist '("elixir" . "\\.eex\\'"))
              (add-to-list 'web-mode-engines-alist '("phoenix" . "\\.[lh]eex\\'"))

              ;; Use // instead of /* as the default comment delimited in JS
              (setf (alist-get "javascript" web-mode-comment-formats nil nil #'equal)
                    "//")

              (add-hook 'web-mode-hook
                         (defun +web--fix-js-comments-h ()
                           "Fix comment handling in `web-mode' for JavaScript."
                           (when (member web-mode-content-type '("javascript" "jsx"))
                             ;; For some reason the default is to insert HTML comments even
                             ;; in JavaScript.
                             (setq-local comment-start "//")
                             (setq-local comment-end "")
                             ;; Needed since otherwise the default value generated by
                             ;; `comment-normalize-vars' will key off the syntax and think
                             ;; that a single "/" starts a comment, which completely borks
                             ;; auto-fill.
                             (setq-local comment-start-skip "// *"))))

              )


;;
;; (after! pug-mode
;;   (set-company-backend! 'pug-mode 'company-web-jade))
;; (after! web-mode
;;   (set-company-backend! 'web-mode 'company-css 'company-web-html))
;; (after! slim-mode
;;   (set-company-backend! 'slim-mode 'company-web-slim))


;; (when (modulep! +lsp)
;;   (add-hook! '(html-mode-local-vars-hook
;;                html-ts-mode-local-vars-hook
;;                web-mode-local-vars-hook
;;                nxml-mode-local-vars-hook)
;;              :append #'lsp!))


;; (use-package! html-ts-mode  ; 30.1+ only
;;   :when (modulep! +tree-sitter)
;;   :defer t
;;   :init
;;   (set-tree-sitter! 'html-mode 'html-ts-mode
;;     `((html :url "https://github.com/tree-sitter/tree-sitter-html"
;;             :rev ,(if (< (treesit-library-abi-version) 15) "v0.23.0" "v0.23.2")))))


;; (use-package! mhtml-ts-mode  ; 31+ only
;;   :when (modulep! +tree-sitter)
;;   :defer t
;;   :init
;;   (set-tree-sitter! 'mhtml-mode 'mhtml-ts-mode 'html))
